// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:weao/data/database/hive_models.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveCachedResultAdapter());
    registerAdapter(HiveFavoriteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HiveCachedResultAdapter());
    registerAdapter(HiveFavoriteAdapter());
  }
}
